-- India Clay Oven: initial schema.
--
-- All access goes through the Next.js server with the secret key, which
-- bypasses RLS. RLS is enabled with no policies so the publishable key
-- (visible in the browser) can read or write nothing. When owner login is
-- added, grant the authenticated owner access with policies here.

create table public.restaurants (
  id            text primary key,
  name          text not null,
  tagline       text not null,
  cuisine       text not null,
  phone         text not null,
  email         text not null,
  address       jsonb not null,
  hours         jsonb not null,
  order_email   jsonb not null,
  owner         jsonb not null,
  tax_rate      numeric(6, 4) not null check (tax_rate >= 0 and tax_rate < 1),
  delivery_fee  numeric(8, 2) not null check (delivery_fee >= 0),
  updated_at    timestamptz not null default now()
);

create table public.categories (
  id             text primary key,
  restaurant_id  text not null references public.restaurants (id) on delete cascade,
  name           text not null,
  note           text,
  sort           integer not null
);
create index categories_restaurant_sort on public.categories (restaurant_id, sort);

create table public.menu_items (
  id             text primary key,
  restaurant_id  text not null references public.restaurants (id) on delete cascade,
  category_id    text not null references public.categories (id) on delete restrict,
  name           text not null,
  description    text,
  price          numeric(8, 2) not null check (price >= 0),
  image          text not null,
  available      boolean not null default true,
  badges         text[] not null default '{}',
  signature      boolean not null default false,
  sort           integer not null
);
create index menu_items_restaurant_sort on public.menu_items (restaurant_id, sort);

create table public.orders (
  id              text primary key,
  restaurant_id   text not null references public.restaurants (id) on delete cascade,
  -- Customer-facing order number. Seeded demo orders use 1044-1048.
  number          integer generated by default as identity (start with 1049) unique,
  placed_at       timestamptz not null default now(),
  customer        jsonb not null,
  type            text not null check (type in ('pickup', 'delivery')),
  timing          text not null check (timing in ('asap', 'scheduled')),
  requested_for   timestamptz not null,
  items           jsonb not null,
  subtotal        numeric(8, 2) not null,
  tax             numeric(8, 2) not null,
  delivery_fee    numeric(8, 2) not null,
  total           numeric(8, 2) not null,
  status          text not null default 'new'
                    check (status in ('new', 'in_progress', 'ready', 'completed')),
  email_delivery  jsonb not null,
  notes           text
);
create index orders_restaurant_placed on public.orders (restaurant_id, placed_at desc);

alter table public.restaurants enable row level security;
alter table public.categories  enable row level security;
alter table public.menu_items  enable row level security;
alter table public.orders      enable row level security;
